apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: micropayment-ssl
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: hello@yelinaung.xyz
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: micropayment-ssl
   # Enable the HTTP-01 challenge provider
   http01: {}
